# Generated by Django 2.2.2 on 2019-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=100)),
                ('first_published_date', models.DateTimeField()),
                ('last_published_date', models.DateTimeField()),
                ('num_bathrooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_floors', models.IntegerField()),
                ('num_recepts', models.IntegerField()),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
        ),
    ]
