# Generated by Django 2.2.2 on 2019-08-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190825_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area_name',
            new_name='post_town',
        ),
        migrations.AddField(
            model_name='property',
            name='outcode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
