# Generated by Django 2.2.2 on 2019-08-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190825_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
