# Generated by Django 2.2.2 on 2019-08-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_property_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('listing_id', models.CharField(max_length=20)),
                ('post_town', models.CharField(max_length=100)),
                ('outcode', models.CharField(max_length=20)),
                ('first_published_date', models.DateTimeField()),
                ('last_published_date', models.DateTimeField()),
                ('num_bathrooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_floors', models.IntegerField()),
                ('num_recepts', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
