# Generated by Django 2.2.2 on 2019-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='first_published_date',
            new_name='first_published_date_day',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='last_published_date',
            new_name='first_published_date_month',
        ),
        migrations.RemoveField(
            model_name='save',
            name='post_town',
        ),
        migrations.AddField(
            model_name='save',
            name='first_published_date_year',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='last_published_date_day',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='last_published_date_month',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='last_published_date_year',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
