# Generated by Django 2.2.2 on 2019-08-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190827_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='first_published_date_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='save',
            name='first_published_date_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='save',
            name='first_published_date_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='save',
            name='last_published_date_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='save',
            name='last_published_date_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='save',
            name='last_published_date_year',
            field=models.CharField(max_length=20),
        ),
    ]
