# Generated by Django 2.2.2 on 2019-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190827_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='username',
            field=models.CharField(max_length=21),
        ),
    ]
