# Generated by Django 2.2.2 on 2019-08-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190827_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
