# Generated by Django 2.2.2 on 2019-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='property_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
