# Generated by Django 2.2.2 on 2019-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190828_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_id',
            field=models.CharField(max_length=21),
        ),
    ]
