# Generated by Django 2.2.2 on 2019-08-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190828_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
