# Generated by Django 2.2.2 on 2019-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_property_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
