# Generated by Django 2.2.2 on 2019-08-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
