# Generated by Django 2.2.2 on 2019-08-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21)),
                ('recommend', models.CharField(max_length=1000)),
            ],
        ),
    ]
