# Generated by Django 2.2.2 on 2019-08-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_recommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
