# Generated by Django 2.2.2 on 2019-09-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
