# Generated by Django 2.2.2 on 2019-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=21)),
                ('post_town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('unit1', models.CharField(max_length=20)),
                ('unit2', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=20)),
                ('last_published_date_day', models.CharField(max_length=20)),
                ('last_published_date_month', models.CharField(max_length=20)),
                ('last_published_date_year', models.CharField(max_length=20)),
                ('num_bathrooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_floors', models.IntegerField()),
                ('num_recepts', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
